---
title: "Research Plan"
---

# Primary Chapter Concepts

1. Explain how Rasmussen and Ghahramani define a pseudolikelihood for $\phi$ and show how one can sample from the resulting pseudo-posterior. Evaluate the effectiveness and reasonableness of this approximation.

2. Test the iMGPE algorithm on multidimensional data with $p$ inputs. Compare a single clustering lengthscale parameter to having $p$ such parameters.

# Chapter 2 Plan

1.  Abstract

2.  Introduction: reintroduce the iMGPE algorithm, noting that the distributions of the clustering parameters are computationally intractable as they are currently defined.

3.  Rasmussen and Ghahramani define a pseudo-conditional for $\phi$ as follows for use in a Metropolis-Hastings sampling step.
$$p^*(\phi|z,\alpha)\approx \prod_{i=1}^n p(z_i|z_{-i},\phi,\alpha) \times p(\phi)$$ 

Define a pseudo-conditional for $\alpha$ based on similar principles.
$$p^*(\alpha|z,\phi)\approx \prod_{i=1}^n p(z_i|z_{-i},\phi,\alpha) \times p(\alpha)$$
Show that these pseudo-conditionals are computationally tractable.

4. With some preparation, the true conditional distribution for $\phi$ can be calculated for $n\leq 10$. Plot the pseudo-conditionals for a given cluster assignment and $\alpha$ using a small $n$ data set. Repeat over a range of values for $z$, $\alpha$, and $n$. Comment on the quality of the approximation and how it varies with $n$ in particular. Extrapolate to larger values of $n$?

5. Fit an iMGPE model to a toy data set with $n\leq 10$, learning the clustering parameters via either their pseudo-conditionals or their true conditionals. The Markov chain provides us with an approximation of $p(\phi|X,y)$, allowing us to compare the approximations for the true and pseudo-conditionals.

6. Compare the iMGPE model with fixed $\alpha$ and $\phi$ to the model that learns them. Fit models using both approaches to a toy data set and compare their performance, perhaps through predictions on a test set. Note how learning additional parameters affects the model's time to convergence. Repeat on a real data set.

7. Conclusions

# Chapter Concepts

1: Compare the fully Bayesian version of iMGPE described by Rasmussen et al. with the partially Bayesian version I have used where the parameters of the GP experts are fit with maximum likelihood estimation. Compare their theoretical properties and evaluate the accuracy and precision of the estimates of each.

2: Replace the Modified Chinese Restaurant Process presented by the authors with another, better defined, clustering step such as the Distance Dependent CRP presented by Blei and Frazier. Compare the theoretical tractability and theoretical properties of each distribution.

3: Modify the clustering step or the GP expert step of the iMGPE algorithm to accept categorical variables as covariates. Experiment with different approaches to find the most reliable and computationally efficient method of incorporating categorical covariate information.

4: Modify the iMGPE algorithm to handle very large data sets (large $n$). In theory, iMGPE should already handle this by partitioning the data. The authors supplement this with the rather brute force suggestion of simply forbidding the construction of clusters of size greater than some threshold. We could study the effectiveness of the current algorithm and explore alternative methods of restricting maximum cluster size or requiring a minimum number of clusters. Another direction is to include big data methods such as Vecchia approximation in the fitting of GP experts, so that we can handle very large clusters.

5: Incorporate deep GP experts into the iMGPE algorithm. I am of two minds regarding the utility of this modification. The practical benefit of deep GPs is that multiple layers of GPs can fit to non-Gaussian models, handling data features like outliers, discontinuities, and heteroskedasticity better than a single GP. The iMGPE algorithm was already supposed to help with these same issues by partitioning the data in each iteration into clusters so that the data in each cluster is appropriate for a single GP. On the other hand, it is not certain that iMGPE is as effective at this as deep GPs are or that we could not improve both methods by combining them.

6: Modify the iMGPE algorithm to include a variable selection step. This is often done in a Bayesian way by using a vector of Bernoulli parameters $\pi_{1:p}= (\pi_1,\dots, \pi_p)\sim \prod_{j=1}^p Bern(\gamma_j)$ to represent which of $p$ variables are selected. My first thought was to draw a new instance of $\pi_{1:p}$ for each cluster so that we could let different variables be relevant in different parts of the data. However, as clusters do not carry over between iterations of the algorithm, we would need to make sure the conditional distributions for the $\pi_{1:p}$ are dependent on the input values.

7: Modify the iMGPE algorithm to accept functional inputs or outputs. Identify or develop a reasonable method of measuring the distance between two functions and of clustering similar functions. Consider whether functional inputs should be handled differently for the purposes of clustering and GP expert sampling.

8: Explore how one might define priors for the concentration or kernel parameters of the Modified Chinese Restaurant Process or the distance-dependent CRP. Consider whether it is justifiable to choose these priors, or fix initial values, based on the input data itself.

9: Explain how Rasmussen and Ghahramani define a pseudolikelihood for $\phi$ and show how one can sample from the resulting pseudo-posterior. Evaluate the effectiveness and reasonableness of this approximation.

10: Test the iMGPE algorithm on multidimensional data with $p$ inputs. Compare a single clustering lengthscale parameter to having $p$ such parameters.
