---
title: "Proofs"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
options(tinytex.verbose = TRUE)
```

## Proof 1

Here, I present a formal proof that given the Modified Chinese Restaurant Process used by Rasmussen and Ghahramani, a valid joint distribution over cluster indicators can be derived from Brook's lemma.

Let $X=(X_1,\dots,X_n)$ be a vector of covariate information for $n$ data points, where each $X_i$ may also be a vector. Let $z$ be a vector of indicator variables of length $n$ indicating the cluster assignments of the points. Assume $z$ is generated by the Modified CRP with the following probabilities of point $z_i$ being assigned to cluster $j$ given all other points.

$$P(z_i=j|z_{-i},\dots)\propto \begin{cases} \begin{align}
&\frac{n-1}{n+\alpha-1}\frac{\sum_{i'\neq i,z_{i'}=j} K_{\phi}(X_i,X_{i'})}{\sum_{i'\neq i} K_{\phi}(X_i,X_{i'})} & \text{ for } j=1,\dots,J^{-i}\\
&\frac{\alpha}{n+\alpha-1} & \text{ for } j=J^{-i}+1
\end{align}\end{cases}$$

Assume $\alpha >0$ and $n\geq 2$. Assume the kernel function $K_{\phi}:\mathbb{X}^2\to (0,\infty)$. That is, the kernel function returns a finite positive scalar value always. Then the ratio of kernel components in the conditional probability above is always in the interval $(0,1]$, since the sum in the numerator is over a subset of the values in the denominator. Note that if the numerator was equal to $0$, that would imply that $z_i$ is in a cluster by itself, so the indicator function on $S_i^C$ would cancel that term anyways.

Now we can apply Brook's lemma. For a given cluster assignment $z$, let $S_i$ be the event that the $i^{th}$ observation is clustered by itself in $z$ and let $S_i^C$ be its complement. Let $z^*_i \equiv \{1,\dots,i-1,z_{i+1:n}\}$. Assume $p(z'=1:n|\alpha,\phi)$ is proportional to $\left(\frac{\alpha}{n+\alpha-1}\right)^n$ with an unknown normalizing constant. Then we know the pmf up to its normalizing constant.

$$p(z|\alpha,\phi)\propto (n+\alpha-1)^{-n}\prod_{i=1}^n\left((n-1)\frac{\sum_{i'\neq i,z^*_{i'}=j}K_{\phi}(X_i,X_{i'})}{\sum_{i'\neq i}K_{\phi} (X_i,X_{i'})}I(S_i^C) + \alpha I(S_i) \right)$$

By what we have established before, we know that $p(z|\alpha,\phi)$ is always finite and non-negative.

There are only a finite number of possible cluster arrangements, so there is always a finite, non-negative normalizing constant constructed as the inverse sum of $p^*(z|\alpha,\phi)$ over all possible $z$. Thus, there is a valid joint distribution for the cluster assignment indicators for any value of $n$.

## Proof 2

Here, I present a formal proof that the Modified Chinese Restaurant Process is a stochastic process via the Kolmogorov Extension Theorem.

### Kolmogorov Extension Theorem

Let $T$ represent an interval (thought of as "time") and let $n\in \mathbb{N}$. For each $k\in \mathbb{N}$ and finite sequence of distinct times $t_1,\dots,t_k\in T$, let $\nu_{t_1,\dots,t_k}$ be a probability measure on $(\mathbb{R}^n)^k$. Suppose that these measures satisfy two conditions:

- For all permutations $\pi$ of $1,\dots,k$ and measureable sets $F_i\subseteq \mathbb{R}^n$, $\nu_{t_{\pi(1)},\dots,t_{\pi(k)}}(F_{\pi(1)}\times \dots \times F_{pi(k)}) =\nu_{t_1,\dots,t_k} (F_1\times \dots \times F_k)$.

- For all measureable sets $F_i\subseteq \mathbb{R}^n$ and $m\in \mathbb{N}$, $\nu_{t_1,\dots,t_k} (F_1\times \dots \times F_k) =\nu_{t_1,\dots,t_k,t_{k+1},\dots,t_{k+m}}\left(F_1\times \dots \times F_k\times (\mathbb{R}^n)^m\right)$.

Then there exists a probability space $(\Omega,F,\mathbb{P})$ and a stochastic process $X:T\times\Omega \to \mathbb{R}^n$ such that $\nu_{t_1,\dots,t_k} (F_1\times \dots \times F_k) =\mathbb{P}(X_{t_1}\in F_1,\dots, X_{t_k}\in F_k)$.

### Application to MCRP

Let $X=(X_1,\dots,X_n)$ be a vector of covariate information for $n$ data points, where each $X_i$ may also be a vector. Let $z$ be a vector of indicator variables of length $n$ indicating the cluster assignments of the points. Assume $z$ is generated by the Modified CRP as defined in Proof 1. Then the probability mass function $p(z|\alpha,\phi)$ up to a normalizing constant is

$$p(z|\alpha,\phi)\propto (n+\alpha-1)^{-n}\prod_{i=1}^n\left((n-1)\frac{\sum_{i'\neq i,z^*_{i'}=j}K_{\phi}(X_i,X_{i'})}{\sum_{i'\neq i}K_{\phi} (X_i,X_{i'})}I(S_i^C) + \alpha I(S_i) \right)$$

Then let $\pi$ be a permutation of $1,\dots,n$ and let $z_{\pi}$ be a permutation of $z$ according to $\pi$. Then 

$$p(z_{\pi}|\alpha,\phi)\propto (n+\alpha-1)^{-n}\prod_{i=1}^n\left((n-1)\frac{\sum_{i'\neq i,z^*_{\pi,i'}=j}K_{\phi}(X_{\pi(i)},X_{\pi(i')})}{\sum_{i'\neq i}K_{\phi} (X_{\pi(i)},X_{\pi(i')})}I(S_i^C) + \alpha I(S_i) \right)$$
$$= (n+\alpha-1)^{-n}\prod_{i=1}^n\left((n-1)\frac{\sum_{i'\neq i,z^*_{i'}=j}K_{\phi}(X_i,X_{i'})}{\sum_{i'\neq i}K_{\phi} (X_i,X_{i'})}I(S_i^C) + \alpha I(S_i) \right)$$

Note that the normalizing constants for $z_{\pi}$ and $z$ are defined as the inverse sum of the unnormalized pmf over all possible permutations of $z$ or $z_{\pi}$. As the unnormalized pmfs are equal, the normalizing constants are equal. Thus, $p(z|\alpha,\phi)=p(z_{\pi}|\alpha,\phi)$, completing the first condition of the Kolmogorov Extension Theorem.

Now note that by the Modified CRP algorithm, you construct a partition by adding points one at a time. Then the $n^{th}$ point has no effect on how the previous $n-1$ points are partitioned, so $p(z_{1,\dots,n}|\alpha,\phi) = \int p(z_{1,\dots,n+m}|\alpha,\phi) dz_{n+1}\dots dz_{n+m}$. This completes the second condition of the Kolmogorov Extension Theorem.

As both conditions have been met, we conclude that the sequence of discrete random variables $z_1,\dots$ is a stochastic process.
