---
title: "References"
---

M. Blei, D., & I. Frazier, P. (2010). Distance Dependent Chinese Restaurant Processes. Journal of Machine Learning Research. [https://jmlr.org/papers/volume12/blei11a/blei11a.pdf](https://jmlr.org/papers/volume12/blei11a/blei11a.pdf)

Rasmussen, C. E., & Ghahramani, Z. (2001). Infinite mixtures of Gaussian process experts. Neural Information Processing Systems, 14, 881–888. [http://learning.eng.cam.ac.uk/zoubin/papers/iMGPE.pdf](http://learning.eng.cam.ac.uk/zoubin/papers/iMGPE.pdf)

Ruth, W. (2024). A Review of Monte Carlo-based Versions of the EM Algorithm. [https://arxiv.org/pdf/2401.00945](https://arxiv.org/pdf/2401.00945)

Lawrence, N. D. (2021). Deep Gaussian Processes: A Motivation and Introduction. [https://inverseprobability.com/talks/notes/deep-gaussian-processes-a-motivation-and-introduction.html](https://inverseprobability.com/talks/notes/deep-gaussian-processes-a-motivation-and-introduction.html)

Foti, N., & Williamson, S. (2015). A Survey of Non-exchangeable Priors for Bayesian Nonparametric Models. IEEE Transactions on Pattern Analysis and Machine Intelligence, 37, no. 2, 359-371 [https://www.researchgate.net/publication/233720862_A_Survey_of_Non-Exchangeable_Priors_for_Bayesian_Nonparametric_Models](https://www.researchgate.net/publication/233720862_A_Survey_of_Non-Exchangeable_Priors_for_Bayesian_Nonparametric_Models)

Sun, S., & Xu, X. (2011). Variational Inference for Infinite Mixtures of Gaussian Processes With Applications to Traffic Flow Prediction. IEEE Transactions on Intelligent Transportation Systems, 12, no. 2, 466-475, doi: 10.1109/TITS.2010.2093575.

Gorur, D., Rasmussen, C. E., (2009). Dirichlet Process Gaussian Mixture Models: Choice of the Base Distribution. Journal of Computer Science and Technology, 25(4), 615-626. [https://mlg.eng.cam.ac.uk/pub/pdf/GoeRas10.pdf](https://mlg.eng.cam.ac.uk/pub/pdf/GoeRas10.pdf)

Gelfand, A. E., Kottas, A., & MacEachern, S. N. (2005). Bayesian Nonparametric Spatial Modeling With Dirichlet Process Mixing. Journal of the American Statistical Association, 100(471), 1021–1035. https://doi.org/10.1198/016214504000002078
